from __future__ import annotations

import html
import json
from pathlib import Path

from pydantic import BaseModel


class AuditReportWriter:
    """Write a portable JSON and HTML snapshot for a completed audit run."""

    def __init__(self, artifacts_root: Path) -> None:
        self.artifacts_root = artifacts_root.resolve()

    def write(self, result: BaseModel) -> tuple[Path, Path]:
        payload = result.model_dump(mode="json")
        package_id = payload["context"]["package_id"]
        run_id = payload["context"]["run_id"]
        target = (self.artifacts_root / package_id / run_id).resolve()
        if self.artifacts_root not in target.parents:
            raise ValueError("report path escapes artifacts root")
        target.mkdir(parents=True, exist_ok=True)
        json_path = target / "report.json"
        html_path = target / "report.html"
        json_path.write_text(
            json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        html_path.write_text(self._html(payload), encoding="utf-8")
        return json_path, html_path

    @staticmethod
    def _html(payload: dict) -> str:
        context = payload["context"]
        gate = payload["release_gate"]
        finding_rows = "".join(
            "<tr>"
            f"<td><span class='sev {html.escape(item['severity'])}'>{html.escape(item['severity'])}</span></td>"
            f"<td><b>{html.escape(item['category'])}</b><small>{html.escape(item['source_agent'])}</small></td>"
            f"<td>{html.escape(item['description'])}</td>"
            f"<td><code>{html.escape(', '.join(item['evidence_ids']))}</code></td>"
            "</tr>"
            for item in payload["findings"]
        )
        evidence_rows = "".join(
            f"<li><b>{html.escape(item['type'])}</b><code>{html.escape(item['id'])}</code>"
            f"<span>sha256 {html.escape(item['sha256'][:16])}…</span></li>"
            for item in payload["evidence"]
        )
        return f"""<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>OJGuard · {html.escape(context['run_id'])}</title><style>
:root{{--bg:#071019;--panel:#0e1c28;--line:#203747;--text:#edf6f7;--muted:#87a0ac;--mint:#79f2c4;--red:#ff6b6b;--amber:#ffbf69}}*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--text);font:14px system-ui,"Microsoft YaHei",sans-serif}}main{{max-width:1180px;margin:auto;padding:48px 24px}}header{{display:flex;justify-content:space-between;gap:24px;align-items:end;border-bottom:1px solid var(--line);padding-bottom:24px}}h1{{font-size:40px;margin:8px 0 0}}.brand{{color:var(--mint);font:12px Consolas}}.decision{{color:var(--red);font:700 22px Consolas}}.metrics{{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:24px 0}}.card{{background:var(--panel);border:1px solid var(--line);border-radius:15px;padding:20px}}.card small{{display:block;color:var(--muted);margin-top:5px}}table{{width:100%;border-collapse:collapse}}th,td{{text-align:left;padding:14px;border-bottom:1px solid var(--line);vertical-align:top}}th{{color:var(--muted);font-size:11px}}code{{display:block;color:var(--mint);font:10px Consolas;margin-top:6px;overflow-wrap:anywhere}}.sev{{font:10px Consolas;text-transform:uppercase}}.critical{{color:var(--red)}}.high{{color:var(--amber)}}ul{{list-style:none;padding:0;display:grid;grid-template-columns:1fr 1fr;gap:10px}}li{{padding:15px;border:1px solid var(--line);border-radius:11px}}li span{{display:block;color:var(--muted);font:10px Consolas;margin-top:7px}}footer{{color:var(--muted);font-size:11px;margin-top:28px}}@media(max-width:720px){{header{{display:block}}.metrics,ul{{grid-template-columns:1fr}}table{{display:block;overflow:auto}}}}
</style></head><body><main><header><div><span class="brand">OJGUARD / EVIDENCE REPORT</span><h1>{html.escape(context['package_id'])}</h1><small>{html.escape(context['run_id'])}</small></div><div><small>RELEASE GATE</small><div class="decision">{html.escape(gate['decision'])}</div></div></header>
<section class="metrics"><div class="card"><b>{len(payload['findings'])}</b><small>confirmed findings</small></div><div class="card"><b>{len(payload['evidence'])}</b><small>evidence artifacts</small></div><div class="card"><b>{html.escape(context['stage'])}</b><small>workflow stage</small></div></section>
<section class="card"><h2>Findings</h2><table><thead><tr><th>Severity</th><th>Category</th><th>Description</th><th>Evidence</th></tr></thead><tbody>{finding_rows}</tbody></table></section>
<section class="card" style="margin-top:16px"><h2>Evidence index</h2><ul>{evidence_rows}</ul></section>
<footer>Generated by OJGuard. This report records deterministic execution evidence; it is not a human release approval.</footer></main></body></html>"""
