<script setup lang="ts">
const agents = [
  { name: 'Judge Manager', role: 'Team Leader', color: 'mint', duties: '拆解任务 · 汇总证据 · 执行规则门禁' },
  { name: 'Specification Auditor', role: 'Worker 01', color: 'blue', duties: '题面 · 配置 · Validator 契约' },
  { name: 'Solution Analyst', role: 'Worker 02', color: 'amber', duties: '算法 · 数值范围 · 风险假设' },
  { name: 'Adversarial Test Engineer', role: 'Worker 03', color: 'red', duties: '边界 · 差分 · 错解驱动测试' },
  { name: 'Checker Auditor', role: 'Worker 04', color: 'violet', duties: '输出校验 · 绕过 · 严重证据复核' },
]
</script>

<template><section class="page"><div class="page-head"><div><h2>真实协作，不在前端演戏。</h2><p>AgentTeams v1.2.0 提供 Matrix 房间、Manager–Workers 编排、MinIO 共享文件与人工介入；OJGuard 保存结构化产品状态与可重放证据。</p></div><a class="ghost-button" href="http://127.0.0.1:18088/#/login" target="_blank">打开 Element 原始轨迹 ↗</a></div>
  <article class="panel topology"><div class="layer human"><small>HUMAN CONTROL PLANE</small><b>参赛者 / 审核员</b><span>补丁审批 · 风险接受 · 发布确认</span></div><i>↓</i><div class="layer matrix"><small>AGENTTEAMS · MATRIX</small><b>透明协作房间</b><span>任务委派 · @mention · Heartbeat · 人工介入</span></div><i>↓</i><div class="agent-grid"><div v-for="agent in agents" :key="agent.name" class="agent" :class="agent.color"><small>{{ agent.role }}</small><b>{{ agent.name }}</b><span>{{ agent.duties }}</span></div></div><i>↓</i><div class="bottom-grid"><div class="layer"><small>OJGUARD MCP · :8020</small><b>受控工具边界</b><span>检查 · Runner · Evidence · 门禁</span></div><div class="layer"><small>DOCKER RUNNER</small><b>无网络执行沙箱</b><span>CPU · 内存 · 时间 · 输出限制</span></div><div class="layer"><small>STATE & TRACE</small><b>SQLite + JSONL</b><span>Finding · Evidence · Approval</span></div></div></article>
  <div class="three-column boundaries"><article class="panel"><small>L1</small><h3>Agent 可执行</h3><p>读取受控题包、提出假设、调用 MCP 探针、生成候选 Diff。</p></article><article class="panel"><small>L2</small><h3>首次人工批准</h3><p>审阅证据与 Diff 后，系统才写入独立工作副本。</p></article><article class="panel"><small>L3</small><h3>二次人工确认</h3><p>完整回归通过后确认发布候选；初赛不连接真实 OJ 发布。</p></article></div>
</section></template>

<style scoped>.topology{text-align:center}.topology>i{display:block;color:var(--mint);font-style:normal;margin:10px}.layer{padding:18px;border:1px solid var(--line);border-radius:13px;background:rgba(255,255,255,.018)}.layer small,.layer b,.layer span{display:block}.layer small{font:9px 'DM Mono';color:var(--mint)}.layer b{margin-top:8px}.layer span{color:var(--muted);font-size:10px;margin-top:5px}.human{max-width:440px;margin:auto;border-color:rgba(255,191,105,.3)}.matrix{max-width:650px;margin:auto}.agent-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:9px}.agent{padding:16px 10px;border:1px solid var(--line);border-radius:12px;background:#0a151f}.agent small,.agent b,.agent span{display:block}.agent small{font:9px 'DM Mono';color:var(--mint)}.agent b{font-size:11px;margin-top:9px}.agent span{font-size:9px;color:var(--muted);margin-top:6px}.agent.blue small{color:var(--blue)}.agent.amber small{color:var(--amber)}.agent.red small{color:var(--red)}.agent.violet small{color:#b99cff}.bottom-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.boundaries{margin-top:18px}.boundaries small{font:10px 'DM Mono';color:var(--mint)}.boundaries h3{font-size:14px}.boundaries p{color:var(--muted);font-size:11px;line-height:1.6}@media(max-width:900px){.agent-grid{grid-template-columns:1fr 1fr}.bottom-grid{grid-template-columns:1fr}}</style>
